"""Option-length balancing: removes the 'longest option is correct' cue.
Each entry replaces option TEXTS (same order as authored; rationales kept)."""
from core import ITEMS

B = {
 "m1-reas-01": ["Clinical reasoning: gathering, interpreting and deciding from multiple sources of information",
                "Administration and scoring of the most widely used standardized language and speech tests",
                "The names, purposes and age ranges of the major standardized tests in the field",
                "Writing a professional diagnostic report that satisfies insurance and IEP reviewers"],
 "m2-int-02": ["Standardized: one fixed battery for every client",
               "Thorough: as much relevant information as possible",
               "Uses a variety of assessment methods",
               "Tailored to the individual client's background"],
 "m2-hip-02": ["Every school-based SLP, regardless of setting", "Health care providers who transmit records",
               "Health plans and insurers", "Business associates of covered providers"],
 "m3-case-02": ["A failed hearing screen (moderate sensorineural loss) and motor sequencing issues on the oral mech exam",
                "A standardized language test showing a severe receptive language disorder in Spanish",
                "Evidence from family interviews that the difficulties were a dialect difference",
                "Aspiration of thin liquids on a videofluoroscopic swallow study after transfer"],
 "m4-std-01": ["Translate the test and keep reporting the English norms",
               "Repeat or reword items for the client",
               "Score according to the question's intent",
               "Add more trial questions before the items"],
 "m4-int-02": ["Direct your questions to the interpreter to relay",
               "Remain in the room and observe the interpreter",
               "Use brief sentences at a natural speaking rate",
               "Introduce the client to the interpreter first"],
 "m5-meth-02": ["Information from clients and others", "Observations (naturalistic or structured)",
                "Standardized (norm or criterion) tests", "Dynamic assessment (test-teach-retest)"],
 "m5-acc-06": ["Whether it changes what is measured or the protocol, or only access",
               "Whether it raises the client's score on the subtest being given",
               "Whether it was done for a client with a documented disability",
               "Whether it is written into the client's current IEP or plan"],
 "m6-ca-07": ["30 or 31 days, depending on the month borrowed from", "Always exactly 30 days, for every month",
              "Always exactly 31 days, for every month", "28 days, to be conservative in every case"],
 "m6-bc-02": ["Credit items below the basal, stop at the ceiling, calculate the raw score",
              "Continue testing through item 35 to confirm the ceiling before stopping",
              "Go back and administer items 1-9 to confirm the basal before scoring",
              "Stop testing at item 13 because a basal has now been established"],
 "m9-q-02": ["The WHO ICF (functioning, disability and health)", "The IDEA eligibility and FAPE framework",
             "The ASKED cultural competence model", "The BID three-phase interpreter process"],
 "m9-fi-04": ["Trouble following multi-step directions limits his independent seatwork",
              "His receptive language standard score was 79 on the CELF-5",
              "He scored at the 8th percentile on the expressive vocabulary test",
              "He was cooperative and attentive throughout the entire testing session"],
 "m10-sh-02": ["EHR records can be shared across health care organizations", "EHRs are paper records, while EMRs are digital records",
               "EMRs are exempt from HIPAA because they stay inside one clinic", "EHRs contain only billing and insurance information"],
 "m11-c-01": ["Two ear infections (18 mo-2 yr) and no full audiological evaluation",
              "She walked at about 13 months and crawled at about 9 months",
              "An older cousin did not talk much until about age 3",
              "She reacts to sounds and usually turns when her name is called"],
 "m11-c-03": ["Do not volunteer it; the examiner must learn to ask", "Mention it briefly during the examiner's closing summary",
              "Hand the examiner the parent sheet so nothing is missed", "Stop the interview and remind the examiner to ask it"],
 "m11-c-04": ["Current hearing and middle-ear status, given his ear history", "A cognitive test to rule out an intellectual disability",
              "An age-equivalent score for articulation to share with the teacher", "A swallowing evaluation because of his history of PE tubes"],
 "m11-k-01": ["Say it's usually too complex to pin on one cause; show compassion",
              "Name the most likely single cause so the parent has some closure",
              "Tell the parent the cause is unknowable and move straight to testing",
              "Refer the question to the child's pediatrician without further comment"],
 "m11-k-02": ["'Thank you for coming in. Any apprehensions about the evaluation?'",
              "'Most parents bring children in much earlier; what happened?'",
              "'Did you know early intervention is much more effective?'",
              "'Who in the family made the decision to wait on this?'"],
 "m12-p-02": ["UV sterilization of the room between every client", "Respiratory hygiene", "Appropriate client placement", "Clean and disinfect the environment"],
 "m12-t-03": ["It isn't standardized and has no psychometric foundation", "It is done only during the observation stage of the process",
              "It takes less than five minutes to complete with most clients", "It is usually performed by an assistant rather than the SLP"],
 "m13-pos-01": ["A structural difference or habitual resting pattern", "Cranial nerve VII weakness under movement demands",
                "A submucous cleft affecting the facial muscles", "Normal development that needs no documentation"],
 "m13-air-02": ["Pressure sounds (/s/, p/b/t/d, 'big puppy'), listening for nasal air", "Mirror under the nostrils during quiet nasal breathing",
                "The client watches the mirror while smiling broadly", "Mirror placed on the tongue while saying a long 'ah'"],
 "m13-rest-01": ["Cueing erases the natural resting posture you meant to see", "Verbal instructions are prohibited during any part of an OPE",
                 "Rest posture can only be observed while the client is in the lobby", "Clients typically refuse later tasks after being given instructions"],
 "m13-jl-04": ["Buccal (cheek) mechanism", "Soft palate (velum)", "Lips (orbicularis oris)", "Jaw stability only"],
 "m14-tr-03": ["They can protrude but not elevate, so protrusion looks 'fine'", "They are only detectable when the TRMR falls below 80%",
               "They occur almost exclusively in adults, not children", "They cause hypernasality that hides the restriction"],
 "m14-pa-01": ["The tongue isn't habitually elevating to that area", "A submucous cleft of the hard palate",
               "Normal adult anatomy that needs no comment", "A torus palatinus (bony protuberance)"],
 "m14-ddk-01": ["A motor planning/sequencing (programming) deficit", "Dysarthria or weakness of the articulators",
                "Neuromuscular involvement with fatigue breakdown", "Typical development for a young child"],
 "m14-doc-01": ["High narrow palate limiting tongue contact, distorting alveolars",
                "High-arched palate noted on visual inspection today",
                "Palate abnormal; refer to ENT for further evaluation",
                "Palate within normal limits except for a high arch"],
 "m15-ra-03": ["To see how rate affects the client's communication", "To compare the client with age norms for eligibility",
               "To determine the client's mean length of utterance", "To establish a baseline for DDK Method 2 timing"],
 "m15-ph-01": ["At what syllable length does articulation decrease?", "What is the client's standard score on this task?",
               "How many utterances are in the client's sample?", "Which of the client's languages is dominant?"],
 "m16-d-04": ["Better accuracy with REDUCED support", "Supplying the correct model before every attempt",
              "Reusing only the exact pretest items", "Timing how long the retest takes"],
 "m17-n-02": ["Explaining why an event happened", "Identifying the story's setting", "Identifying the main characters", "Predicting what happens next"],
}

B.update({
 "xb-mc-02": ["Is this a language/cultural difference or an underlying disorder?", "Which standardized test has the largest and most recent normative sample?",
              "Does the client speak English well enough to take the standardized test?", "Is an interpreter available in the client's primary language today?"],
 "xb-mc-09": ["As well as or better than about 16% of same-age peers", "Your child answered about 16% of the test items correctly",
              "Your child scored better than about 84% of same-age peers", "Your child scored 16 points below the average standard score"],
 "xb-mc-13": ["Why the evaluation was requested", "Date of evaluation and date of birth", "Referral source", "The clinician's name and credentials"],
 "xb-mc-19": ["Single-word/short-phrase and conversational samples", "The client's standardized receptive vocabulary score",
              "The client's AMR and SMR diadochokinetic rates", "Published norms for oral reading words per minute"],
 "xb-mc-20": ["The client's raw score on each subtest", "Voice quality during conversation", "Use of gestures while communicating", "Turn-taking with a partner"],
})

B.update({
 "ba-maya-01": ["'Can you tell me a little about Maya and what brings you in?'", "'How many words does Maya say right now, would you guess?'",
                "'Has Maya had her hearing tested by anyone recently?'", "'Was Maya born premature, or right around her due date?'"],
 "ba-maya-03": ["Recommend a full audiological evaluation before interpreting language", "Diagnose a conductive hearing loss from the ear-infection history",
                "Drop the concern because she usually turns when her name is called", "Postpone all speech-language assessment until she turns 3"],
 "ba-maya-08": ["Parent report is often more accurate than clinic performance", "Parent report should be discarded when the child won't perform",
                "Only standardized scores are valid for children under three", "Toddlers usually perform best with unfamiliar adults present"],
 "ba-rep-04": ["His true score likely lies in 70-82, all below the −1 SD line", "His true score is exactly 76; the interval is just a formality",
               "A 90% interval for the same score would be wider than 70-82", "The interval proves he is 'significantly below average' on her slide"],
 "ba-rep-06": ["'He scored as well as or better than about 5 in 100 kids his age.'", "'Jordan's language is functioning like a typical 6-year-old's.'",
               "'Jordan got about 76 percent of the test items correct.'", "'Jordan is 24 points behind where he should be right now.'"],
 "ba-cld-01": ["A language history: which languages, how often, where", "A second English-only standardized language test",
               "Her age equivalent on the English-normed test", "Her percentile rank on the English-normed test"],
 "ba-cld-03": ["Points AWAY from impairment (non-improvers are more likely impaired)", "Confirms a language disorder because she needed teaching at all",
               "Is invalid because dynamic assessment isn't used with CLD clients", "Replaces the need to collect a language history from the family"],
 "bb-adu-07": ["Seek converging evidence, such as an oral mechanism exam", "Diagnose from the perceptual evaluation alone since it fits",
               "Stop testing, since the tool already passed questions 1-5", "Give an aphasia test next to confirm what you suspect"],
 "bb-sel-01": ["Choosing by availability, familiarity and colleague talk", "Relying too heavily on psychometric properties of tests",
               "Overusing dynamic assessment with preschool children", "Requiring too many reference standards per study"],
 "bb-sel-04": ["Sensitivity under ~80% means it may miss disordered children", "Specificity is too low, so it will over-identify typical children",
               "Both values are acceptable, so there is no real concern", "The test must be unreliable because the two values differ"],
 "bb-sel-07": ["Client/patient/caregiver perspectives", "External evidence from the literature", "Internal evidence from the client's data", "Clinical expertise and judgment"],
 "bb-eth-02": ["Current hearing/middle-ear status (screen or recent audiology)", "His age-equivalent score on an articulation test",
               "His current reading level and letter knowledge", "A swallowing study because of the PE-tube history"],
 "bb-eth-05": ["Reduced tongue-tip elevation with jaw compensation; limits /l/ contact; assess speech impact",
               "Tongue restriction noted during the oral mechanism examination today",
               "Tongue within normal limits for structure, function and range of motion",
               "Suspected tongue tie observed on inspection; refer for surgical release now"],
 "bb-eth-06": ["Errors reduce intelligibility to teachers and peers, limiting class participation", "Standard score of 78 on the articulation test given today",
               "He produced /w/ for /r/ in 12 of the 15 target words tested", "Mother reports concern about how other people understand him"],
})

B.update({"bb-adu-09": ["Nasal air escape on pressure sounds: possible VPI", "Normal, healthy nasal breathing at rest",
                        "Hyponasality caused by nasal obstruction", "Poor lip seal letting air escape orally"]})

def apply():
    idx = {i["id"]: i for i in ITEMS}
    for k, texts in B.items():
        it = idx[k]
        assert len(texts) == len(it["options"]), k
        for o, t in zip(it["options"], texts):
            o["t"] = t

# Second pass (after measuring 53% "correct is longest" across MC): even out the 30 strongest cues.
B2 = {
 "m4-std-01": ["Translate the test and keep reporting the English norms", "Repeat or reword items for the client when needed",
               "Score according to the intent of the question asked", "Add more trial questions before the test items begin"],
 "m5-meth-01": ["To draw a conclusion about an individual's communicative abilities", "To obtain a standard score that qualifies the client for services",
                "To compare the client with a normative sample of same-age peers", "To determine the client's long-term and short-term therapy goals"],
 "m7-band-08": ["72 is below average; 66 is significantly below average", "Both are significantly below average, since both are under 75",
                "Both are below average; the bands only split at 55", "72 is average; 66 is below average on her bell curve"],
 "m9-set-01": ["Whether communication difficulties adversely affect educational performance", "Whether the student is safe to swallow thin liquids during school lunch",
               "A broader range of functional outcomes across home, work and community", "A brief cognitive-linguistic screen until the student is medically stable"],
 "m9-fi-02": ["An adult after a stroke does poorly on timed naming yet communicates well with compensatory strategies",
              "A child scores below average on a vocabulary test and also struggles in peer conversation at recess",
              "A bilingual child scores low on an English-only test normed on monolingual English speakers",
              "A client's standard score changes by several points when the same test is repeated a month later"],
 "m12-p-02": ["UV sterilization of the room between every client", "Respiratory hygiene and cough etiquette",
              "Appropriate client placement in the clinic", "Cleaning and disinfecting the environment"],
 "m13-four-02": ["Dissociation", "Mobility (range)", "Grading (force)", "Stability (hold)"],
 "m13-jl-03": ["Mentalis (hyperactive) compensating for orbicularis oris", "Orbicularis oris compensating for a weak mentalis",
               "Masseter compensating for a weak buccinator", "Buccinator compensating for a weak mentalis"],
 "m15-na-01": ["Cognitive organization and language sequencing", "Phonological awareness and decoding of print",
               "Turn-taking and topic maintenance in dialogue", "Morphology and syntax only, at the sentence level"],
 "m15-na-02": ["Receptive vocabulary norms", "Articulation of connected speech", "Voice quality and fluency", "Reading abilities"],
 "m16-i-01": ["When the client does not match the normative profiles of available tests", "When the clinician simply prefers not to use standardized tests",
              "Whenever the client's eligibility decision requires a standard score", "Only for adults with aphasia who cannot complete standardized testing"],
 "m17-n-01": ["Determine whether the client understands the story", "Count the number of different words in the retell",
              "Score the microstructure of the client's retell", "Teach a story framework with modeling and cues"],
 "xa-mc-07": ["Every score derived from it may be inaccurate if it is wrong", "It is the score used directly for eligibility decisions",
              "It is the score easiest for parents to understand", "It sets the starting point and basal for the next test"],
 "xa-mc-13": ["Summarizing the major points discussed", "Introductions of everyone present", "Purpose of the meeting", "Structure of the meeting"],
 "xa-mc-20": ["The clinician's expertise and how representative the data are", "The test publisher's norms and standardization sample",
              "Whether a teaching phase was included in the task", "The number of standardized tests also given that day"],
 "xb-mc-14": ["Test in both languages within the same item to save time", "Use culturally appropriate materials and stimuli",
              "Be prepared to modify the assessment plan as needed", "Use an interpreter or translator if one is needed"],
 "xb-mc-15": ["The client's preferred reinforcement schedule", "Progression of the behavior over time",
              "Responses to the behavior by others", "Involvement of other professionals so far"],
 "ba-maya-06": ["Eye contact and joint attention", "Voice quality during play", "Fluency of her vocalizations", "Communication breakdown and repair"],
 "ba-cld-04": ["An interpreter, briefed first and observed during the meeting", "A translator, because the meeting is formal and recorded",
               "Ana herself, since she speaks both languages at home", "No one; send an English-only case history form home"],
 "bb-adu-01": ["Targeted and time-sensitive, e.g., a bedside swallow screen", "A full standardized language battery before anything else",
               "Curriculum-based language sampling from classroom work", "A broad functional-outcomes battery across all settings"],
 "bb-adu-04": ["Possible dysarthria or weakness", "A motor planning or sequencing deficit", "Typical aging of the speech system", "A submucous cleft of the palate"],
 "bb-sel-02": ["It is not a valid tool for diagnosis; find another test", "Use it for diagnosis but lower the cutoff score",
               "Use it if the norms include speakers of the child's dialect", "Use it for diagnosis, reporting a 99% confidence interval"],
 "bb-sel-03": ["Does the normative sample reflect the person being tested?", "Can I use this test for diagnosis, given its stated purpose?",
               "Does the test consistently measure the person's ability?", "Is there acceptable evidence of diagnostic accuracy?"],
 "bb-eth-03": ["Dynamic assessment (stimulability-type probing)", "Informal assessment, with no teaching involved",
               "Norm-referenced testing against same-age peers", "Case history gathered from his mother"],
 "bb-eth-06": ["Errors reduce his intelligibility to teachers and peers, limiting participation", "Standard score of 78 on the articulation test administered today",
               "He produced /w/ for /r/ in 12 of the 15 target words on the probe list", "Mother reports concern about how well other people understand him"],
 "ba-cld-07": ["Rely on English norms because instruction is in English", "Assess her abilities in both of her languages",
               "Be sensitive and respectful toward the family", "Use culturally appropriate materials and stimuli"],
 "ba-cld-08": ["Use an ethnographic, non-judgmental approach; be thoughtful in how you ask", "Tell the family the evaluation cannot proceed without full answers",
               "Assume her early history was typical and skip that section", "Ask the classroom teacher to complete the family history form instead"],
 "bb-sel-09": ["An accommodation; standard scores generally remain valid", "A modification; the norms are now invalid for this child",
               "Dynamic assessment, because support was added", "A reason to switch to a screening test instead"],
}
B.update(B2)


B3 = {
 "m2-eth-01": ["Within their competence, based on education, training and experience", "Using only standardized tests normed on the client's population",
               "After obtaining a physician's referral for every client", "Once the client's insurance has authorized the evaluation"],
 "m3-case-02": ["A failed hearing screen (moderate SNHL) and motor sequencing issues on the oral mech exam",
                "A standardized language test showing a severe receptive language disorder in Spanish",
                "Evidence from family interviews that the difficulties reflected a dialect difference",
                "Aspiration of thin liquids on a videofluoroscopic swallow study after his transfer"],
 "m3-acc-01": ["Gold/reference standard", "Normative sample", "Confidence interval", "Cutoff score alone"],
 "m3-acc-02": ["Those values were for a different target disorder (elevated thresholds)", "The values fall below the typical 80% benchmark for accuracy",
               "It did not report group differences, so the values are invalid", "Specificity above sensitivity means the test over-identifies"],
 "m4-role-02": ["Administer a standardized test normed on the client's group", "Attend cultural events held in the client's community",
                "Interview members of the client's cultural community", "Watch movies and TV shows from the client's cultural group"],
 "m4-da-01": ["The client does not demonstrate improvement after teaching", "The client improves quickly after only brief teaching",
              "The client scores low on the pretest before any teaching", "The client needs an interpreter to complete the pretest"],
 "m5-man-01": ["The age equivalent the client is expected to earn", "The purpose of the test and what it measures",
               "The population for whom the test is designed", "How to administer and score the test correctly"],
 "m5-nc-01": ["How does my client's performance compare to an expected level?", "How does my client compare to the average of same-age peers?",
              "How does my client respond to teaching during the session?", "How consistent are my client's scores across administrations?"],
 "m6-ca-02": ["Test scores must be compared to the correct age-based normative group", "It determines which basal and ceiling rule the manual will use",
              "It is needed first in order to calculate the client's raw score", "It replaces the need for an adjusted age in older children"],
 "m6-ca-07": ["30 or 31 days, depending on the month borrowed from", "Always exactly 30 days, whatever the month borrowed",
              "Always exactly 31 days, whatever the month borrowed", "28 days in every case, to be conservative with age"],
 "m7-pr-01": ["Performed as well as or better than 75% of the norm group", "Answered 75% of the test items correctly on the test",
              "Scored better than only 25% of the norm group", "Scored 75 points on the standard-score scale"],
 "m9-q-02": ["The WHO ICF (functioning, disability and health)", "The IDEA eligibility and FAPE framework for schools",
             "The ASKED cultural competence model from ASHA", "The BID three-phase interpreter process (Langdon)"],
 "m10-sh-01": ["Begin with next steps so caregivers know the plan before results", "Use jargon-free language, illustrations, charts and diagrams",
               "Emphasize the client's strengths along with the concerns", "Allow the family time to process what they have heard"],
 "m13-pos-04": ["Airway and breathing patterns", "Possible hearing loss", "Cranial nerve XII damage", "Dental malocclusion only"],
 "m13-air-02": ["Pressure sounds (/s/, p/b/t/d, 'big puppy'), listening for nasal air", "A mirror under the nostrils during quiet nasal breathing at rest",
                "The client watches the mirror while smiling broadly", "A mirror placed on the tongue while saying a long 'ah'"],
 "m13-rest-04": ["A 30-minute therapy session", "An 8-hour school day", "A 60-minute evaluation", "A full night's sleep"],
 "m14-pa-01": ["The tongue isn't habitually elevating to that area", "A submucous cleft of the hard palate behind it",
               "Normal adult anatomy that needs no comment at all", "A torus palatinus (a bony protuberance) forming"],
 "m14-doc-01": ["High narrow palate limiting tongue contact, distorting alveolars", "High-arched palate noted on visual inspection during today's exam",
                "Palate abnormal in shape; refer to ENT for further evaluation", "Palate within normal limits except for a high, narrow arch"],
 "m15-sa-01": ["Long enough to be representative: 50-100 minimum utterances", "Exactly 100 complete and fully intelligible utterances",
               "At least 200 utterances in every case, for any client", "1-2 minutes of connected speech from one activity"],
 "m16-o-01": ["Only in completely unstructured natural settings", "During a standardized assessment session",
              "While interacting with family members", "In the classroom during instruction"],
 "xa-mc-06": ["Enlarging stimulus materials for a student with a visual impairment", "Giving additional prompts that are not specified in the manual",
              "Repeating items when the test manual does not allow repetition", "Translating an English-standardized test into Spanish on the spot"],
 "xa-mc-12": ["Targeted and time-sensitive, such as a bedside swallowing screen", "A comprehensive language battery completed before any screening",
              "Curriculum-based language sampling from his daily activities", "A broad functional-outcomes battery across communication settings"],
 "bb-eth-02": ["Current hearing/middle-ear status (screen or recent audiology)", "His age-equivalent score on an articulation test given today",
               "His current reading level and his letter knowledge", "A swallowing study because of his PE-tube history"],
 "bb-eth-04": ["Listener familiarity with the client", "Number of utterances collected", "His DDK rate on puh-tuh-kuh", "Test-retest reliability of the test"],
 "bb-eth-05": ["Reduced tongue-tip elevation with jaw compensation; limits /l/ contact; assess speech impact",
               "Tongue restriction noted during the oral mechanism examination today; will continue to monitor",
               "Tongue within normal limits for structure, function and range of motion at this time",
               "Suspected tongue tie observed on inspection; refer for a surgical release right away"],
 "bb-adu-09": ["Nasal air escape on pressure sounds: possible VPI", "Normal, healthy nasal breathing during speech",
               "Hyponasality caused by a nasal obstruction", "Poor lip seal letting the air escape orally"],
}
B.update(B3)

# Fourth pass: in each of these a distractor is now at least as long as the key.
B4 = {
 "m13-rest-04": ["A 30-minute therapy session", "An 8-hour school day in the classroom", "A 60-minute evaluation", "A full night's sleep"],
 "m3-acc-01": ["Gold/reference standard", "Normative standardization sample", "Confidence interval", "Cutoff score alone"],
 "m13-pos-04": ["Airway and breathing patterns", "Possible hearing loss", "Cranial nerve XII (hypoglossal) damage", "Dental malocclusion only"],
 "m16-o-01": ["Only in completely unstructured natural settings", "During a standardized assessment session in the clinic room",
              "While interacting with family members", "In the classroom during instruction"],
 "m12-p-02": ["UV sterilization of the room between every client", "Respiratory hygiene and cough etiquette for everyone present",
              "Appropriate client placement in the clinic", "Cleaning and disinfecting the environment"],
 "xa-mc-16": ["Developmental, medical and hearing history", "Speech and communication concerns and their impact at home",
              "School, family and parent priorities", "Summarize and close"],
 "m14-smc-03": ["The mucosa over the defect is intact", "It causes no speech or resonance symptoms at all", "It is visible only on X-ray", "It occurs only with a cleft lip"],
 "m4-diff-02": ["Difficulty only with vocabulary in the newer language", "A tendency to repeat what is heard, in both of the languages",
                "Family history of language-learning disability", "Atypical nonverbal communication"],
 "xa-mc-13": ["Summarizing the major points discussed", "Introductions of everyone present at the meeting", "Purpose of the meeting", "Structure of the meeting"],
 "xa-mc-20": ["The clinician's expertise and how representative the data are", "The test publisher's norms and the makeup of its standardization sample",
              "Whether a teaching phase was included in the task", "The number of standardized tests also given that day"],
 "ba-cld-07": ["Rely on English norms because instruction is in English", "Assess her abilities in both of her languages, not only in English",
               "Be sensitive and respectful toward the family", "Use culturally appropriate materials and stimuli"],
 "xa-mc-03": ["Aspiration of thin and mildly thick liquids on videofluoroscopy", "Moderate sensorineural hearing loss found on the audiological evaluation",
              "No swallowing difficulty, confirming the bedside result", "A submucous cleft palate"],
 "m3-acc-02": ["Those values were for a different target disorder (elevated thresholds)", "The values fall below the typical 80% benchmark that the video recommends",
               "It did not report group differences, so the values are invalid", "Specificity above sensitivity means the test over-identifies"],
 "m13-jl-03": ["Mentalis (hyperactive) compensating for orbicularis oris", "Orbicularis oris compensating for a weak, underactive mentalis",
               "Masseter compensating for a weak buccinator", "Buccinator compensating for a weak mentalis"],
 "m15-dd-01": ["Method 2: measuring the seconds it takes to produce a number of syllables", "Method 1: counting how many syllables are produced within a set number of seconds",
               "Counting total words per minute", "Timing a 1-2 minute conversational sample"],
 "m12-f-03": ["Velopharyngeal inadequacy", "Labial weakness", "Enlarged tonsils", "Short lingual frenulum (tongue tie)"],
 "m14-te-01": ["The upper first molar sits forward relative to the lower first molar; the lower jaw appears retruded",
               "The cusp of the upper first molar fits into the groove of the lower first molar, so the bite lines up",
               "The upper first molar sits behind the lower first molar; the lower jaw appears prominent", "The top and bottom front teeth don't come together"],
 "xb-mc-16": ["Neurological impairment or muscle weakness", "A submucous cleft of the palate", "Tongue thrust",
              "Normal variation that needs no follow-up at all"],
 "m14-tr-03": ["They can protrude but not elevate, so protrusion looks 'fine'", "They are only detectable once the TRMR falls below the 80% cutoff",
               "They occur almost exclusively in adults, not children", "They cause hypernasality that hides the restriction"],
 "bb-eth-06": ["Errors reduce his intelligibility to teachers and peers, limiting participation", "Standard score of 78 on the articulation test administered today",
               "He produced /w/ for /r/ in 12 of the 15 target words on today's probe list", "Mother reports concern about how well other people understand him"],
 "m11-s-01": ["Start with open-ended questions, then ask specific follow-up questions", "Start with specific yes/no questions, then move to open-ended questions",
              "Ask every question on the handout in order", "Start with medical history before the primary concern"],
 "ba-cld-01": ["A language history: which languages, how often, where", "A second English-only standardized language test for comparison",
               "Her age equivalent on the English-normed test", "Her percentile rank on the English-normed test"],
 "m7-norm-01": ["They guarantee that the test is valid for every client", "They allow comparison of the client to same-age peers",
                "They make standardized scores possible", "They support diagnostic and eligibility decisions"],
 "xb-mc-14": ["Test in both languages within the same item to save time", "Use culturally appropriate materials and stimuli",
              "Be prepared to modify the assessment plan as the session unfolds", "Use an interpreter or translator if one is needed"],
 "xb-mc-15": ["The client's preferred reinforcement schedule", "Progression of the behavior over time, since it began",
              "Responses to the behavior by others", "Involvement of other professionals so far"],
 "m7-pr-01": ["Performed as well as or better than 75% of the norm group", "Answered 75% of the test items correctly on the test form",
              "Scored better than only 25% of the norm group", "Scored 75 points on the standard-score scale (mean 100)"],
 "m6-ca-02": ["Test scores must be compared to the correct age-based normative group", "It determines which basal and ceiling rule the test manual will use",
              "It is needed first in order to calculate the client's raw score", "It replaces the need for an adjusted age in older children"],
 "m10-an-01": ["Assimilating and analyzing findings", "Obtaining the case history", "Administering the standardized tests", "Writing up the recommendations"],
 "m15-sa-01": ["Long enough to be representative: 50-100 minimum utterances", "Exactly 100 complete and fully intelligible utterances",
               "At least 200 utterances in every case, for any client of any age", "1-2 minutes of connected speech from one activity"],
 "xa-mc-07": ["Every score derived from it may be inaccurate if it is wrong", "It is the score used directly for eligibility decisions in schools",
              "It is the score easiest for parents to understand", "It sets the starting point and basal for the next test"],
 "ba-cld-04": ["An interpreter, briefed first and observed during the meeting", "A translator, because the meeting is formal and will be recorded",
               "Ana herself, since she speaks both languages at home", "No one; send an English-only case history form home"],
 "bb-adu-09": ["Nasal air escape on pressure sounds: possible VPI", "Normal, healthy nasal breathing during connected speech",
               "Hyponasality caused by a nasal obstruction", "Poor lip seal letting the air escape orally"],
 "m7-ci-03": ["The possibility of measurement error around the obtained score", "The range of ages covered by the norms",
              "The difference between the basal and ceiling items", "The percentage of the norm group that scored below the client on the test"],
 "bb-sel-08": ["Different reference standards for the two groups introduce bias", "The index test was not described in enough detail to replicate",
               "Teacher report cannot be a reference standard in any study", "The sample was too small"],
}
B.update(B4)
apply()
